# Generated by Django 3.0.6 on 2021-06-23 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minatech', '0004_blog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog',
            new_name='blogs',
        ),
    ]
